name: Build and Publish
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image 
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Save image to file
        run: docker save my-image-name:$(date +%s) > image.tar

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Load image from job1
        run: docker load < image.tar
      - name: Publish to Registry 
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ducky111/simple-container-wizard
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}
